/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ABCCookSchema {
  [k: string]: unknown;
}
/**
 * The internal DAG of a recipe: what the LLM extracts, what the scheduler consumes.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "CookingGraph".
 */
export interface CookingGraph {
  /**
   * Cuisine, when the source states or implies one.
   */
  cuisine: string | null;
  /**
   * Stable graph id.
   */
  id: string;
  /**
   * Every ingredient the recipe lists.
   */
  ingredients: Ingredient[];
  /**
   * Every unit of work.
   */
  nodes: Node[];
  /**
   * Servings the quantities are stated for.
   */
  servings: number;
  source: SourceRef;
  /**
   * Ordered stages; every node's `stage` must appear here.
   */
  stages: Stage[];
  /**
   * Total time the original recipe claimed. Sanity-checks extraction (§5.8).
   */
  stated_total_min: number | null;
  /**
   * Recipe title, e.g. "Kadai Paneer".
   */
  title: string;
}
/**
 * One ingredient line from the source recipe.
 *
 * A `prep_note` is a hint that a prep node exists: "2 onions, finely chopped"
 * implies a `chop_onion` node even when no written step mentions chopping.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "Ingredient".
 */
export interface Ingredient {
  /**
   * Ingredient grouping, e.g. "For the masala" / "For garnish".
   */
  group: string | null;
  /**
   * Stable id, e.g. "ing_onion".
   */
  id: string;
  /**
   * Display name, e.g. "Onion".
   */
  name: string;
  /**
   * Optional ingredients are exempt from the consumption invariant (§5.5).
   */
  optional?: boolean;
  /**
   * Preparation stated on the ingredient line, e.g. "finely chopped".
   */
  prep_note: string | null;
  /**
   * Quantity, or null when the recipe gives none.
   */
  qty: number | null;
  /**
   * Unit, e.g. "medium", "g", "tbsp".
   */
  unit: string | null;
}
/**
 * One unit of work in the cooking graph.
 *
 * `kind` and `attention` are separate on purpose. `attention` decides whether the
 * node occupies the cook and therefore whether it creates a wait window; `kind`
 * decides how it renders. Scheduler code must branch on `attention` only.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "Node".
 */
export interface Node {
  /**
   * Whether the cook is occupied. `unattended` and `periodic` create windows.
   */
  attention: 'hands_on' | 'periodic' | 'unattended';
  /**
   * Ingredient ids and/or component ids this node uses up.
   */
  consumes?: string[];
  /**
   * Node ids that must COMPLETE before this node may start.
   */
  depends_on?: string[];
  /**
   * Sensory finish signal, e.g. "onions light golden, oil separating".
   */
  doneness_cue?: string | null;
  /**
   * Pessimistic duration; window-safety checks use this.
   */
  duration_max: number;
  /**
   * Optimistic duration in minutes.
   */
  duration_min: number;
  /**
   * Duration the plan displays and schedules on.
   */
  duration_typical: number;
  /**
   * Stable id, e.g. "cook_base".
   */
  id: string;
  /**
   * Full sentence(s) shown in step mode.
   */
  instruction: string;
  /**
   * Whether the cook can drop this mid-way and return. Gates `periodic` windows.
   */
  interruptible: boolean;
  /**
   * Render classification. Not used by the scheduler.
   */
  kind: 'prep' | 'active' | 'passive' | 'combine' | 'finish';
  /**
   * UI heading, four words or fewer.
   */
  label: string;
  /**
   * Freshness ceiling: minutes this may finish before its consumer starts (§4.5).
   */
  max_lead_min?: number | null;
  /**
   * Component id this node yields, e.g. "comp_base".
   */
  produces?: string | null;
  /**
   * Id of the stage this node belongs to; must exist in `stages`.
   */
  stage: string;
  /**
   * The resource this node contends for.
   */
  station: 'burner' | 'oven' | 'counter' | 'sink' | 'fridge' | 'none';
  /**
   * Optional aside shown in step mode.
   */
  tip?: string | null;
}
/**
 * Where a recipe came from.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "SourceRef".
 */
export interface SourceRef {
  /**
   * When the import ran.
   */
  imported_at: string;
  /**
   * url / image / pasted text.
   */
  kind: 'url' | 'image' | 'text';
  /**
   * The URL, the image reference, or the pasted text itself.
   */
  value: string;
}
/**
 * A named group of nodes: Prep, Cook Base, Add Veggies, Finish.
 *
 * Stages are user-facing and ordered; the Plan view groups by them.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "Stage".
 */
export interface Stage {
  /**
   * Key into the stage palette in docs/DESIGN_SYSTEM.md.
   */
  color_key: string;
  /**
   * Stable id, e.g. "cook_base".
   */
  id: string;
  /**
   * User-facing name, e.g. "Cook the base".
   */
  label: string;
}
/**
 * The scheduled, renderable output the user sees.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "CookingPlan".
 */
export interface CookingPlan {
  /**
   * Node ids on the longest path.
   */
  critical_path: string[];
  /**
   * Id of the graph this plan was computed from.
   */
  graph_id: string;
  /**
   * serial_min - total_min. The number the product is arguing for.
   */
  saved_min: number;
  /**
   * Every node, placed on the timeline.
   */
  scheduled: ScheduledNode[];
  /**
   * Sum of all typical durations, done one at a time.
   */
  serial_min: number;
  /**
   * Makespan of the scheduled plan.
   */
  total_min: number;
  /**
   * Safety-check findings (§4.5). "degraded" means extraction fell back.
   */
  warnings?: string[];
  /**
   * Wait windows derived from the timeline.
   */
  windows: WaitWindow[];
}
/**
 * One node placed on the timeline.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "ScheduledNode".
 */
export interface ScheduledNode {
  /**
   * Minutes from the start of cooking.
   */
  end_min: number;
  /**
   * Id of the node in the source graph.
   */
  node_id: string;
  /**
   * Whether the cook is busy for this interval. Follows `Node.attention`.
   */
  occupies_cook: boolean;
  /**
   * Order within the window. 0 is the task the UI promotes as "start with this".
   */
  rank_in_window?: number | null;
  /**
   * Minutes from the start of cooking.
   */
  start_min: number;
  /**
   * Set when this ran inside another node's wait window.
   */
  window_id?: string | null;
}
/**
 * An unattended interval the scheduler filled with prep work.
 *
 * User-facing as "while this cooks". Capacity is deliberately below the host node's
 * duration — see §4.3 for the multipliers and why they exist.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "WaitWindow".
 */
export interface WaitWindow {
  /**
   * Node ids, in the order the cook should do them.
   */
  assigned: string[];
  /**
   * Usable minutes, after the safety multiplier.
   */
  capacity_min: number;
  /**
   * The unattended or periodic node whose duration creates it.
   */
  host_node_id: string;
  /**
   * Stable window id.
   */
  id: string;
  /**
   * Unused capacity.
   */
  slack_min: number;
  /**
   * Minutes of assigned work.
   */
  used_min: number;
}
/**
 * Every recipe the API can currently serve.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "RecipeListResponse".
 */
export interface RecipeListResponse {
  /**
   * Available recipes, by title.
   */
  recipes: RecipeSummary[];
}
/**
 * One row in the recipe list.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "RecipeSummary".
 */
export interface RecipeSummary {
  /**
   * Slug used in the plan URL.
   */
  id: string;
  /**
   * Servings the quantities are stated for.
   */
  servings: number;
  /**
   * Recipe title, e.g. "Kadai Paneer".
   */
  title: string;
}
/**
 * Everything the Plan view needs, in one round trip.
 *
 * The graph rides along because the plan is node *ids* and timings — the labels,
 * instructions and ingredients the renderer draws all live on the graph. Shipping both
 * keeps the frontend a pure renderer: it joins by id, and computes nothing.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "RecipePlanResponse".
 */
export interface RecipePlanResponse {
  graph: CookingGraph;
  plan: CookingPlan;
  /**
   * Per-stage rollups, in `graph.stages` order. See schedule/rollup.py.
   */
  stages: StageSpan[];
}
/**
 * A stage's footprint on the scheduled timeline.
 *
 * Deliberately NOT part of `CookingPlan`: it is a view over a finished plan, computed
 * by `abc_cook.schedule.rollup`, and adding it to the plan would rewrite all five
 * golden fixtures for a rendering convenience.
 *
 * It exists because the Plan view shows a per-stage minute count, and the frontend is
 * forbidden from deriving one (CLAUDE.md). Stages interleave — in Kadai Paneer `prep`
 * spans 0-19 while `cook_base` spans 3-22 — so a stage is a span, not a block.
 *
 * This interface was referenced by `ABCCookSchema`'s JSON-Schema
 * via the `definition` "StageSpan".
 */
export interface StageSpan {
  /**
   * Wall-clock span of the stage. Overlaps other stages' spans.
   */
  elapsed_min: number;
  /**
   * Latest end among this stage's nodes.
   */
  end_min: number;
  /**
   * `work_min - windowed_work_min`. What the stage's own card still shows.
   */
  inline_work_min: number;
  /**
   * This stage's nodes, in scheduled order.
   */
  node_ids: string[];
  /**
   * Id of the stage in the source graph.
   */
  stage_id: string;
  /**
   * Earliest start among this stage's nodes.
   */
  start_min: number;
  /**
   * Of `work_min`, the minutes absorbed into another stage's wait window.
   */
  windowed_work_min: number;
  /**
   * Sum of `duration_typical` over the stage's nodes.
   */
  work_min: number;
}
